config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
belongs_to :user
validates :title, presence: true, length: { minimum: 6, maximum: 100 }
validates :description, presence: true, length: { minimum: 10, maximum: 300 }
has_many :article_categories
has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end 

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum:25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum:105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be signed in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  before_action :require_user, except: [:show, :index]

  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article 
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
   @article.destroy
   redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end  
  
  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
  @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed in"
      redirect_to articles_path
    else
      render "new"
    end
  end

  def show
    @articles = @user.articles
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own accout"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)  
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username)
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do | article | %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <% if article.user %>
      <td>by <%= link_to article.user.username, user_path(article.user) %></td>
      <% end %> <% if article.categories.any? %>
      <div><%= render article.categories %></div>
      <% end %>
      <td><%= link_to 'Show', article_path(article) %></td>
      <% if logged_in? && (article.user == current_user || current_user.admin?)
      %>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td>
        <%= link_to 'Delete', article_path(article), method: :delete, data: {
        confirm: "Are you sure?" } %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_errors.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented the article from being saved</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

app/views/articles/_form.htm.erb
<%= form_with(model: @article, local: true) do |f| %>

<p>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</p>

<p><%= f.submit %></p>

<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |f| %>

<p>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</p>

<div>
  <%= f.label :category %>
  <div>
    <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt:
    "Make your selection from the list below (can be empty)"}, { multiple:
    true}) %>
  </div>
</div>

<p><%= f.submit %></p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render "errors" %> <%= render "form" %> <%= link_to "Cancle and return to
articles listing", articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<%= render "article" %>

<p><%= link_to "Create new article", new_article_path %></p>

<p><%= link_to "Home", root_path %></p>

<p><%= link_to "About", about_path %></p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render "errors" %> <%= render "form" %> <%= link_to "Return to articles
listing", articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>Autor: </strong>by <%= @article.user.username %></p>
<p><%= link_to gravatar_for(@article.user), user_path(@article.user) %></p>

<% if @article.categories.any? %>
<div><%= render @article.categories %></div>
<% end %>

<p>
  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <%= link_to "Edit", edit_article_path(@article) %> | <%= link_to "Delete",
  article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</p>

<%= link_to "Return to articles listing", articles_path %>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill
badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %> <%= form_with(model: @category,
class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
<div class="form-group row">
  <%= f.label :name, "Category name", class: "col-2 col-form-label text-light"
  %>
  <div class="col-10">
    <%= f.text_field :name, class: "form-control shadow rounded", placeholder:
    "Enter a name" %>
  </div>
</div>

<div class="form-group row justify-content-center">
  <%= f.submit class: "btn btn-outline-light btn-lg" %>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10"><%= render 'form' %></div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to category ]', category_path(@category),
      class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="container">
  <% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-4 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to category.name, category_path(category), class:
            "text-success" %>
            <p class="card-text">
              <%= pluralize(category.articles.count, "article") %>
            </p>
          </h5>
        </div>
        <div class="card-footer text-muted">
          <small
            >Created <%= time_ago_in_words(category.created_at) %> ago, edited
            <%= time_ago_in_words(category.updated_at) %> ago</small
          >
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>Create a new category</h1>
<div><%= render 'form' %></div>
<div><%= link_to '[ Cancel and return to categories ]', categories_path%></div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
<div class="text-center mt-4">
  <%= link_to "Edit category name", edit_category_path(@category), class: "btn
  btn-outline-info" %>
</div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %> <div class="alert alert-<%= name == "notice" ?
"success" : "danger" %> alert-dismissible fade show" role="alert"> <%= msg %> <%
end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %> <%= csp_meta_tag %>
  </head>

  <body>
    <% render "layouts/navigation" %> <% render "layouts/messages" %> <%= yield
    %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to "Articles listing", articles_path %> <%= link_to "Home", root_path
%>

app/views/pages/home.html.erb
<h1>Home</h1>

<% if logged_in? %>
<p>
  <%= link_to "(Admin)" if current_user.admin? current_user.username,
  user_path(current_user) %>
</p>
<p><%= link_to 'Sign-out', logout_path, method: :delete %></p>
<%= link_to "Delete profile", user_path(current_user), method: :delete, data: {
confirm: "Are you sure?" } %> <% else %>
<p><%= link_to 'Sign-in', login_path %></p>
<p><%= link_to 'Sign-up', signup_path %></p>
<% end %>
<br />
<p><%= link_to "Articles listing", articles_path %></p>
<p><%= link_to "About", about_path %></p>
<p><%= link_to "Bloggers", users_path %></p>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
<h2>The following errors prevented the account from being saved</h2>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>

<p>
  <%= f.label :username %><br />
  <%= f.text_field :username, placeholder: "Enter a username" %>
</p>

<p>
  <%= f.label :email %><br />
  <%= f.email_field :email, placeholder: "Enter your email address" %>
</p>

<p>
  <%= f.label :password %><br />
  <%= f.password_field :password, placeholder: "Choose a password" %>
</p>

<p><%= f.submit(@user.new_record? ? "Sign up" : "Update account" ) %></p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render "errors" %> <%= render "form" %> <%= link_to "Return to articles
listing", articles_path %>

app/views/users/index.html.erb
<h1>Alpha Bloggers</h1>

<div>
  <% @users.each do | user | %>
  <p><%= link_to user.username, user %></p>
  <p><%= link_to gravatar_for(user, size: 150), user %></p>
  <p><%= pluralize(user.articles.count, "article") %></p>
  <p><%= link_to 'View Profile', user %></p>
  <% if logged_in? %> <% if user == current_user %>
  <p><%= link_to 'Edit Profile', edit_user_path(user) %></p>
  <% end %> <% if current_user.admin? %>
  <p>
    <%= link_to "Delete profile", user_path(current_user), method: :delete,
    data: { confirm: "Are you sure you want to delete the user account and all
    associated articles?" } %>
  </p>
  <% end %> <% end %> <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render "errors" %> <%= render "form" %> <%= link_to "Return to articles
listing", articles_path %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %> <% if logged_in? && @user == current_user
%>
<p><%= link_to "Edit your profile", edit_user_path(@user) %></p>
<% end %>

<h3>Articles</h3>

<%= render "articles/article" %> <%= link_to "Return to articles listing",
articles_path %>